#!/bin/bash
#
# Create Nextcloud Client Sync Container v1.1
# Author: Scott Shambarger <devel@shambarger.net>
#
# Copyright (C) Scott Shambarger. All rights reserved.
# SPDX-License-Identifier: GPL-2.0-or-later
#
# create-container [ debug ]
#  - creates a persistent container
# create-container run [ debug ]
#  - creates and runs a temporary container in the foreground
#
# debug
#  - replaces the entrypoint with /bin/bash (to examine the startup)

# Options are defined in config file
CONFIG=${CONFIG:-config.conf}

usage() {
  [[ $1 ]] && echo "Unknown option '$1'";
  echo "Usage: ${0##*/} [ run ] [ debug ] | help"
  [[ -z $1 ]]; exit
}

fatal() {
  echo >&2 "$*"
  exit 1
}

[[ -f $CONFIG ]] || fatal "Unable to find config '$CONFIG'"
. "$CONFIG"

# required config
[[ $IMAGE ]] || fatal "Set required IMAGE in '$CONFIG'"
[[ $URL ]] || fatal "Set required URL in '$CONFIG'"
[[ $LOCAL_DIR ]] || fatal "Set required LOCAL_DIR in '$CONFIG'"

# validate directory
[[ -d $LOCAL_DIR ]] || fatal "LOCAL_DIR '$LOCAL_DIR' must exist"

# prefer podman if available
[[ -z $DOCKER ]] && command >/dev/null -v podman && DOCKER=podman
DOCKER=${DOCKER:-docker}
command >/dev/null -v "$DOCKER" || fatal "Unable to locate $DOCKER executable"

# create image if it's missing
"$DOCKER" &>/dev/null inspect "${IMAGE}:latest" || {
  export CONFIG
  ./create-image || exit
}

# if SELinux available, add :Z to volume tags to support labels
VOL_TAG=
command >/dev/null -v getenforce && VOL_TAG=":Z"

# remove any existing container
[[ $NAME ]] && "$DOCKER" &>/dev/null rm -f "$NAME"

ARGS=(--init)

# default name
[[ $NAME ]] && ARGS+=(--name "$NAME")

# Add /netrc if requested
[[ $NETRC ]] && ARGS+=(-v "${NETRC}:/netrc${VOL_TAG}")

# Add /sync-exclude.lst if requested
if [[ $EXCLUDE ]]; then
  # NOTE: name of the remote file impacts how it's used
  # "sync-exclude.lst" is affects all directories
  ARGS+=(-v "${EXCLUDE}:/sync-exclude.lst${VOL_TAG}")
fi

[[ $REMOTE_PATH ]] && ARGS+=(-e "NC_PATH=${REMOTE_PATH}")

vars=(RESTART_SECS FAIL_RETRY_SECS VERBOSE OPTIONS LOG_FILE LOG_MAX_BYTES
      LOG_ARCHIVES SENDMAIL_OPTIONS ERROR_TO ERROR_FROM ERROR_SUBJECT
      ERROR_COUNT ERROR_REMIND_COUNT)

for var in "${vars[@]}"; do [[ ${!var} ]] && ARGS+=(-e "NC_$var=${!var}"); done

DEBUG=
CMD=create

while [[ $1 ]]; do
  case "$1" in
    debug) DEBUG=1; ARGS+=(-t --entrypoint /bin/bash);;
    run) CMD=run;;
    -h|--help|help) usage;;
    *) usage "$1";;
  esac
  shift
done

if [[ $CMD == run ]]; then
  ARGS+=(--rm -i)
else
  if [[ -z $DEBUG ]]; then
    # if restarting... make the container auto-restart
    [[ $RESTART_SECS && $RESTART_SECS -gt 0 ]] && \
      ARGS+=(--restart unless-stopped)
  fi
fi

echo "$DOCKER" $CMD "${CREATE_ARGS[@]}" -e "NC_URL=${URL}" \
     -v "${LOCAL_DIR}:/data${VOL_TAG}" "${ARGS[@]}" "${IMAGE}"

"$DOCKER" $CMD "${CREATE_ARGS[@]}" -e "NC_URL=${URL}" \
          -v "${LOCAL_DIR}:/data${VOL_TAG}" "${ARGS[@]}" "${IMAGE}"
